baseURL = 'https://eoinmotherway.dev/'
languageCode = 'en'
paginate = 5
enableGitInfo = true
enableRobotsTXT = true

[privacy]
  [privacy.youtube]
    privacyEnhanced = true

[params]
    showMenuItems = 3
    showLastUpdated = true
    readingTime = true
    favicon = 'favicon-128.png'

[languages]
    [languages.en]
        languageName = "English"
        title = "Eoin Motherway"
        subtitle = "Making computers go beep and boop"
        copyright = '© 2023 Eoin Motherway'

    [languages.en.params.logo]
        logoText = "Eoin Motherway"
        logoHomeLink = "/"
