baseURL = 'https://yukitsune.dev/'
languageCode = 'en'
theme = 'kitsune'
paginate = 5
enableGitInfo = true
enableRobotsTXT = true

[privacy]
  [privacy.youtube]
    privacyEnhanced = true

[params]
    showMenuItems = 3
    showLastUpdated = true
    readingTime = true
    favicon = 'favicon-128.png'

    [params.twitter]
        # see https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started#card-and-content-attribution
        # do not include @
        creator = "YuKitsune256"

[languages]
    [languages.en]
        languageName = "English"
        title = "Eoin Motherway"
        subtitle = "Making computers go beep and boop"
        copyright = '© 2022 Eoin Motherway'

    [languages.en.params.logo]
        logoText = "Eoin Motherway"
        logoHomeLink = "/"

    [languages.en.menu]
        [[languages.en.menu.main]]
            identifier = "showcase"
            name = "Showcase"
            url = "/showcase"

        [[languages.en.menu.main]]
            identifier = "posts"
            name = "Posts"
            url = "/posts"
