baseURL = 'https://yukitsune.dev/'
languageCode = 'en-au'
title = 'My New Hugo Site'
theme = 'terminal'
paginate = 5
enableGitInfo = true
enableRobotsTXT = true

[params]
    themeColor = "pink"
    showMenuItems = 3
    centerTheme = true
    showLastUpdated = true
    readingTime = true

[params.twitter]
    # set Twitter handles for Twitter cards
    # see https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started#card-and-content-attribution
    # do not include @
    creator = "YuKitsune256"
    site = "https://yukitsune.dev"


[languages]
    [languages.en]
        languageName = "English"
        title = "YuKitsune"
        subtitle = "A simple, retro theme for Hugo"
        owner = ""
        keywords = ""
        copyright = ""
        menuMore = "Show more"
        readMore = "Read more"
        readOtherPosts = "Read other posts"
        newerPosts = "Newer posts"
        olderPosts = "Older posts"
        missingContentMessage = "Page not found..."
        missingBackButtonLabel = "Back to home page"

    [languages.en.params.logo]
        logoText = "YuKitsune"
        logoHomeLink = "/"

    [languages.en.menu]
        
        [[languages.en.menu.main]]
            identifier = "showcase"
            name = "Showcase"
            url = "/showcase"

        [[languages.en.menu.main]]
            identifier = "posts"
            name = "Posts"
            url = "/posts"
