name = "tundra"
license = "MIT"
licenselink = "https://github.com/YuKitsune/tundra/blob/master/LICENSE.md"
description = "A minimalistic theme for Hugo."
homepage = "https://github.com/YuKitsune/tundra/"
tags = ["blog", "clean", "minimal", "simple"]
features = ["blog", "shortcode", "syntax highlighting"]
min_version = 0.74

[author]
  name = "YuKitsune"
  homepage = "https://yukitsune.dev"
  twitter = "https://twitter.com/yukitsune"
